In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [3]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2
v_sub = v1 - v2

In [6]:
print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [7]:
scalar = 2
v_scalar = scalar * v1

In [8]:
print (v_scalar)

[2 4 6]


In [9]:
dot_product = np.dot(v1, v2)

In [10]:
print (dot_product)

32


In [11]:
magnitude_v1 = np.linalg.norm(v1)

In [12]:
print (magnitude_v1)

3.7416573867739413


In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()

B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1,2,3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print ("A+C=\n", matrix_add)
print("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [19]:
matrix_mult = np.dot(A, B)
print("A*B=\n", matrix_mult)

A*B=
 [[ 66  72  78]
 [156 171 186]]


In [20]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [24]:
A = np.array([[2, 3], [4, -1]])
B = np.array([5, 3])
print(A)
print(B)

x = np.linalg.solve(A, B)

print("Solution:\n", x)

[[ 2  3]
 [ 4 -1]]
[5 3]
Solution:
 [1. 1.]


In [29]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)

In [30]:
print("eigenvalue:", e_value)
print("eigenvector:", e_vector)

eigenvalue: [3. 1.]
eigenvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [32]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [33]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [34]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [36]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
            
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [39]:
# Example Usage
A = [[2, 3, -1], [4, -2, 2], [-2, 1, 2]]
b = [5, 6, -1]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [40]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    
    # modifying the original matrix
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i] # Multiplier for row
                # operation
                L[j, i] = factor # Store multiplier in L
                # Update the rows of U
                for k in range(i, n):
                    U[j, k] -= factor * U[i, k]
    return L, U

In [41]:
# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]


In [42]:
print(L@U)

[[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
